### ISSUE TITLE
icu_replace compile script --  pkg-config vs icu-config

### ISSUE THREAD

**Issue by gsker** [gwenn/sqlite-regex-replace-ext#2]
Compiling succeeded but did not produce a good library with this line in the icu_replace.sh script:    

    gcc -fPIC -O2 -Wall -shared -o icu_replace.so icu_replace.c `icu-config --ldflags`

I changed it to this:    

    gcc -fPIC -O2 -Wall -shared -o icu_replace.so icu_replace.c $(pkg-config --libs icu-i18n)

Ubuntu Focal (20.04)   gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Dev package:
    ii  libicu-dev:amd64 66.1-2ubuntu2 amd64        Development files for International Components for Unicode

Just to be complete:

    /sqlite-regex-replace-ext-master>ldd icu_replace.so
        linux-vdso.so.1 (0x00007fff1de86000)
        libicui18n.so.66 => /usr/lib/x86_64-linux-gnu/libicui18n.so.66 (0x00007f5a67d91000)
        libicuuc.so.66 => /usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007f5a67bab000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5a679b9000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5a677d8000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5a67689000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5a6766e000)
        libicudata.so.66 => /usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007f5a65bab000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5a65b88000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5a65b82000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5a680ac000)

**Comment by gwenn** [comment]
Thanks for your report.
`icu-config` is missing ?
If so, I will update the shell script accordingly.

**Comment by gsker** [comment]
`apt-file search icu-config` turns up no Ubuntu 20.04 or debian bullseye package with that file. 

And the likely candidates don't have it in their packages:
`dpkg -L icu-devtools libicu-dev | grep icu-config`
returns nothing.

Also this bug refers to it:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920900

From: http://userguide.icu-project.org/howtouseicu
`Note:  icu-config is deprecated, and no longer recommended for production use. Please use pkg-config files or other options. `
`As of ICU 63.1, icu-config has been deprecated (ICU-10464). icu-config be disabled by default in the future. As of ICU 63.1 enable or disable 63.1 with: --enable-icu-config or --disable-icu-config`
