### ISSUE TITLE
Termination Issue / Incorrect Buffer size

### ISSUE THREAD

**Issue by orangelynx** [gwenn/sqlite-regex-replace-ext#4]
I got incorrect termination of the result string when the Replacement was exactly twice +1 as long as the input. I tried to figure out where exactly the problem occurs, but in the end I wasn't able to find it and due to time constraints, I had to move on with the quick fix, which was to increase the default size of `zOutput` to `4 * nInput + 2`. Also, I noticed that `nInput` should be determined before reading the actual string `zInput`, because otherwise, according to the SQLite docs, the call for `nInput` might invalidate the pointer to `zInput`.

The error occured for me for the inputs `ERROR` as input, `^ERROR$` as program and `GLOBAL.DIAG` as replacement string, however only on the second+ run. I checked however with gdb, for each run (context disgarded by sqlite), the program is recompiled and the error still occurs.

Only applies to the ICU regex replace, the glib had all kinds of other weird behaviour for me.

Just wanted to put this out as a warning, sorry I can't be of more help right now to fix the problem.

**Comment by gwenn** [comment]
https://sqlite.org/c3ref/value_blob.html
> Please pay particular attention to the fact that the pointer returned from sqlite3_value_blob(), sqlite3_value_text(), or sqlite3_value_text16() can be invalidated by a subsequent call to sqlite3_value_bytes(), sqlite3_value_bytes16(), sqlite3_value_text(), or sqlite3_value_text16().

But, as far as know, `sqlite3_value_text16` and then `sqlite3_value_bytes16` is ok.
Are you sure that your text is valid utf-8 or utf-16 ?
Because SQLite is perfectly fine if you store text in another encoding.
But then you cannot use these functions...

**Comment by orangelynx** [comment]
The text was entered manually and is from the ASCII subset. The encoding of the database is set to UTF-8, i checked. Also if it was a wrong encoding, I would surprised that doubling the initial buffer size ~fixes~ circumvents the issue.

**Comment by gwenn** [comment]
So I guess I don't use `uregex_replaceAll` correctly.

**Comment by orangelynx** [comment]
I wouldn't jump to that conclusion. I double checked your code thoroughly, and I couldn't really find anything wrong with it. But I'm also not super familiar with the ICU and sqlite APIs. I think there might be fallpits with respect to buffer size vs capacity, one being bytes the other characters. and whether the capacity includes the null terminator or not. and perhaps icu also has a bug that the null terminator is not taken into account correctly.

I wish I could be more helpful, but that's as far as I got. I just think it's important that this is somehow documented so users of the library are careful.

**Comment by orangelynx** [comment]
Likely we have our pitfall here:
https://github.com/unicode-org/icu/blob/a1383189225c6c3e180182d970a67aedc33be4aa/icu4c/source/i18n/uregex.cpp#L1714
If there's no space for the NULL Terminator, it will put a warning, not an error.

**Comment by gsker** [comment]
This works:
``` 
    sqlite> select regex_replace('aab', 'aab', '1234567');
    1234567
```
This breaks:
```
    sqlite> select regex_replace('ab', 'aab', '1234567');
    a1234567↑
```
Switching to table mode I see that this one breaks (it doesn't in .csv mode):
```
    sqlite> select regex_replace('ab', 'saab', '123456789a');
    +-------------------------------------------+
    | regex_replace('ab', 'saab', '123456789a') |
    +-------------------------------------------+
    | sa123456789aĀ                             |
    +-------------------------------------------+
```

But your example did not fail for me:
```
    sqlite> select regex_replace( "^ERROR$", "ERROR", "GLOBAL.DIAG");
    GLOBAL.DIAG
```
I tried doing it multiple times in the same query and in various output modes.
Interesting behavior.

**Comment by orangelynx** [comment]
Keep in mind that buffer bound violations get you into random territory. the next byte MAY be 0, but doesn't need to be. But then again, the behaviour doesn't seem truly random, which staggers me. Could you try my patch? I didn't get any more broken strings after that.

**Comment by gwenn** [comment]
Could you please give #6 a try ?

**Comment by orangelynx** [comment]
@gwenn thanks, looking good! Not a fan of the loop-style, but i guess to be consistent with the existing icu ext, I'd do the same.

**Comment by gsker** [comment]
I tested with all my examples and they work correctly now.

**Comment by orangelynx** [comment]
#6 merged.
